### ISSUE TITLE
[bugs] Import bugs from WOS

### ISSUE THREAD

**Issue by panwanke** [sophosia/sophosia#56]
An error occurred when I tried to import data from .bib and.ris exported from Web of science. 
But I managed to get into the .bib data exported from zotero. I think the likely reason is that the wos bib-data contains other undefined fields.

```
2index.221ae9c1.js:352 Error: This format is not supported or recognized
    at @invalid (index.221ae9c1.js:41:12873)
    at data$2 (index.221ae9c1.js:41:13176)
    at dataAsync$1 (index.221ae9c1.js:41:13452)
    at chainAsync$1 (index.221ae9c1.js:41:12536)
    at Cite$1.addAsync (index.221ae9c1.js:41:15506)
    at Cite$1.setAsync (index.221ae9c1.js:41:15884)
    at Function.async (index.221ae9c1.js:41:17528)
    at getMeta (index.221ae9c1.js:352:65156)
    at importMeta (index.221ae9c1.js:352:65987)
    at async q (LibraryPage.da42255b.js:1:55056)
```

**Comment by HuntFeng** [comment]
Hi, I am not familiar with Web of Science, do you have any example problematic bib files? I can use them to test the software.

**Comment by HuntFeng** [comment]
Close issue due to no activity
